### ISSUE TITLE
About SWAP.py 

### ISSUE THREAD

**Issue by JinYu1998** [zju-SWJ/RLD#1]
In the [swap](https://github.com/zju-SWJ/RLD/blob/main/mdistiller/distillers/SWAP.py#L13) code, how much does it improve the accuracy of KD if you just use swap, and don't use normalize?

**Comment by zju-SWJ** [comment]
You can refer to our paper (https://arxiv.org/pdf/2408.07703). The swap code corresponds to the LA method, whose corresponding results (Tables 2, 3, and 4) are obtained with just swapping and no normalization.

**Comment by JinYu1998** [comment]
> You can refer to our paper (https://arxiv.org/pdf/2408.07703). The swap code corresponds to the LA method, whose corresponding results (Tables 2, 3, and 4) are obtained with just swapping and no normalization.

Thanks for your reply, I think my problem has been solved.

**Comment by JinYu1998** [comment]
In addition, could you please provide some student models on CIFAR-100 after distillation with RLD.  Thank you~

**Comment by zju-SWJ** [comment]
> In addition, could you please provide some student models on CIFAR-100 after distillation with RLD. Thank you~

You can download the models from https://github.com/zju-SWJ/RLD/releases/download/ckpt/RLD_student.zip

**Comment by JinYu1998** [comment]
> > In addition, could you please provide some student models on CIFAR-100 after distillation with RLD. Thank you~
> 
> You can download the models from https://github.com/zju-SWJ/RLD/releases/download/ckpt/RLD_student.zip

👍, Thanks a lot !
